#!C:\Users\Lenovo\OneDrive - IRESSEF\Documents\DSWB\Project\Training\Workshop_2025\Github\od\test\no-code-test\py\mlenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
